export enum DocumentPrintParamTypeEnum {
    Name,
    FirstName,
    LastName,
    BirthDate,
    Nationality,
    JobPosition,
    Passport,
    Image,
    QrGuid,
    Registration,
    Weapon0,
    Weapon1,
    Weapon2,
    Weapon3,
}
