import lang from "lang";

import type { INavigationMenu } from "./NavigationMenuDrawer";

const menuList: INavigationMenu[] = [
    { name: "home", title: lang.pages.home.title, icon: "home", link: "/", category: "main" },
    { name: "profile", title: lang.pages.profile.title, icon: "profile", link: "/profile", category: "main" },
    {
        name: "qrScanner",
        title: lang.pages.home.qr,
        icon: "qrScanner",
        link: "/qrScanner",
        roles: [["qr"]],
        category: "main",
    },
    //{ name: "links", title: lang.pages.links.title, icon: "links", link: "/links", category: "main" },
    { name: "maps", title: lang.components.map.title, icon: "map", link: "/maps", category: "main" },

    {
        name: "medicalPolicies",
        title: lang.pages.medicalPolicies.title,
        icon: "medicalPolicies",
        link: "/medicalPolicies",
        roles: [["medicalPolicies"]],
        category: "medical",
    },
    {
        name: "medicalSickness",
        title: lang.pages.medicalSickness.title,
        icon: "medicine",
        link: "/medicalSickness",
        roles: [["medicalSickness"]],
        category: "medical",
    },
    {
        name: "medicalInfo",
        title: lang.pages.medicalInfo.title,
        icon: "medicalInfo",
        link: "/medicalInfo",
        roles: [["medicalInfo"], ["medicalInfoAdd"]],
        category: "medical",
    },
    {
        name: "licenses",
        title: lang.pages.licenses.title,
        icon: "licenses",
        link: "/licenses",
        roles: [["licenses"]],
        category: "administrative",
    },
    {
        name: "wanteds",
        title: lang.pages.wanteds.title,
        icon: "wanteds",
        link: "/wanteds",
        roles: [["wanteds"]],
        category: "administrative",
    },

    {
        name: "wanteds2",
        title: lang.pages.wanteds2.title,
        icon: "wanteds2",
        link: "/wanteds2",
        roles: [["wanteds2"]],
        category: "administrative",
    },

    {
        name: "wanteds3",
        title: lang.pages.wanteds3.title,
        icon: "wanteds3",
        link: "/wanteds3",
        roles: [["wanteds3"]],
        category: "administrative",
    },
    {
        name: "taxes",
        title: lang.pages.taxes.title,
        icon: "taxes",
        link: "/taxes",
        roles: [["taxes"]],
        category: "administrative",
    },
    {
        name: "company",
        title: lang.pages.companies.title,
        icon: "company",
        link: "/company",
        roles: [["company"]],
        category: "administrative",
    },
    {
        name: "claims",
        title: lang.pages.claims.title,
        icon: "claims",
        link: "/claims",
        roles: [["claims"]],
        category: "administrative",
    },
    {
        name: "users",
        title: lang.pages.users.title,
        icon: "users",
        link: "/users",
        roles: [["admins"]],
        category: "admin",
    },
    {
        name: "roles",
        title: lang.pages.roles.title,
        icon: "roles",
        link: "/roles",
        roles: [["admins"]],
        category: "admin",
    },
    {
        name: "nationalities",
        title: lang.pages.nationalities.title,
        icon: "list",
        link: "/nationalities",
        roles: [["admins"]],
        category: "admin",
    },
    {
        name: "taxesTypes",
        title: lang.pages.taxesTypes.title,
        icon: "taxesTypes",
        link: "/taxesTypes",
        roles: [["admins"]],
        category: "admin",
    },
    {
        name: "persons",
        title: lang.pages.users.persons,
        icon: "users",
        link: "/persons",
        roles: [["users"]],
        category: "administrative",
    },
    {
        name: "messages",
        title: lang.pages.messages.title,
        icon: "messages",
        link: "/messages",
        roles: [["messages"]],
        category: "administrative",
    },
    {
        name: "shop",
        title: lang.pages.shop.title,
        icon: "shop",
        link: "/shop",
        roles: [["shop"]],
        category: "admin",
    },
    {
        name: "personalities",
        title: lang.pages.personalities.title,
        icon: "secrets",
        link: "/personalities",
        roles: [["admins"]],
        category: "admin",
    },

    {
        name: "documentPrint",
        title: lang.pages.documentPrint.title,
        icon: "print",
        link: "/documentPrint",
        roles: [["admins"]],
        category: "admin",
    },
];

export default menuList;
